home:
  path: /
  controller: App\Controller\HomeController::index
panier:
  path: /panier
  controller: App\Controller\PanierController::index


article_index:
  path: /articles
  controller: App\Controller\ArticleController::index

ajouter:
  path: /ajouter
  controller: App\Controller\AjouterController::index

article_show:
  path: /article/{id}
  controller: App\Controller\ArticleController::show

panier_add:
  path: /panier/add/{id}
  controller: App\Controller\PanierController::addToCart
  methods: POST

app_login:
  path: /login
  controller: App\Controller\SecurityController::login


app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register